<div class="col-md-8">
            <div class="well">

                <ul class="nav nav-tabs">
                    <li class="active"><a href="#1" data-toggle="tab">People</a></li>
                    <li><a class=""href="#2" data-toggle="tab">Phone</a></li>
                </ul>

                <div class="tab-content">
                    <div class="tab-pane active" id="1">
                        <form role="form" action="load" method="post">
                            <fieldset>
                                <legend>Directory</legend>

                                <div class="row">

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="firstname">First Name</label>
                                            <input type="text" class="form-control" id="firstname" name="firstname" placeholder="First Name">
                                        </div>
                                    </div>

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="lastname">Last Name</label>
                                            <input type="text" class="form-control" id="lastname" name="lastname" placeholder="Last Name">
                                        </div>
                                    </div>

                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="middlename">Middle Name</label>
                                            <input type="text" class="form-control" id="middlename" name="middlename" placeholder="Middle Name">
                                        </div>
                                    </div>

                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="suffix">Suffix</label>
                                            <input type="text" class="form-control" id="suffix" name="suffix" placeholder="Suffix">
                                        </div>
                                    </div>

                                    <div class="col-md-2">
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="type" id="person" value="person">
                                                Person
                                            </label>
                                        </div>
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="type" id="org" value="organization">
                                                Organization
                                            </label>
                                        </div>
                                    </div>

                                </div>

                                <div class="row">

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="nickname">Nickname</label>
                                            <input type="text" class="form-control" id="nickname" name="nickname" placeholder="Nickname">
                                        </div>
                                    </div>

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="uniqname">Uniq Name</label>
                                            <input type="text" class="form-control" id="uniqname" name="uniqname" placeholder="Uniqname">
                                        </div>
                                    </div>

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="umid">UM ID</label>
                                            <input type="text" class="form-control" id="umid" name="umid" placeholder="UM ID">
                                        </div>
                                    </div>

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="caenid">CAEN ID</label>
                                            <input type="text" class="form-control" id="caenid" name="caenid" placeholder="CAEN ID">
                                        </div>
                                    </div>

                                </div>

                                <button type="submit" class="btn btn-info">Submit <span class="glyphicon glyphicon-search"></span></button>

                            </fieldset>


                    </div>
                    <div class="tab-pane" id="2">
                        <div class="row">

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="phonenumber">Phone Number</label>
                                    <input type="text" class="form-control" id="phonenumber" name="phonenumber" placeholder="###-###-####">
                                </div>
                            </div>

                        </div>
                    </form>
                    </div>
                </div>

            </div>
        </div>