<div class="col-md-8">
            <div class="well">

                <ul class="nav nav-tabs">
                    <li class="active"><a href="#directory" data-toggle="tab">Directory</a></li>
                    <li><a href="#addresses" data-toggle="tab">Addresses</a></li>
                    <li><a href="#phones" data-toggle="tab">Phones</a></li>
                    <li><a href="#employeeInfo" data-toggle="tab">Employee Info</a></li>
                    <li><a href="#appointments" data-toggle="tab">Appointments</a></li>
                    <li><a href="#phoneList" data-toggle="tab">Phone List</a></li>
                </ul>

                <div class="tab-content">
                    <div class="tab-pane active" id="directory">
                        <form role="form" action="load" method="post">
                            <fieldset>
                                <legend>Directory</legend>

                                <div class="row">

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="firstname">First Name</label>
                                            <input type="text" class="form-control" id="firstname" name="firstname" placeholder="First Name">
                                        </div>
                                    </div>

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="lastname">Last Name</label>
                                            <input type="text" class="form-control" id="lastname" name="lastname" placeholder="Last Name">
                                        </div>
                                    </div>

                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="middlename">Middle Name</label>
                                            <input type="text" class="form-control" id="middlename" name="middlename" placeholder="Middle Name">
                                        </div>
                                    </div>

                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="suffix">Suffix</label>
                                            <input type="text" class="form-control" id="suffix" name="suffix" placeholder="Suffix">
                                        </div>
                                    </div>

                                    <div class="col-md-2">
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="type" id="person" value="person">
                                                Person
                                            </label>
                                        </div>
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="type" id="org" value="organization">
                                                Organization
                                            </label>
                                        </div>
                                    </div>

                                </div>

                                <div class="row">

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="nickname">Nickname</label>
                                            <input type="text" class="form-control" id="nickname" name="nickname" placeholder="Nickname">
                                        </div>
                                    </div>

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="uniqname">Uniq Name</label>
                                            <input type="text" class="form-control" id="uniqname" name="uniqname" placeholder="Uniqname">
                                        </div>
                                    </div>

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="umid">UM ID</label>
                                            <input type="text" class="form-control" id="umid" name="umid" placeholder="UM ID">
                                        </div>
                                    </div>

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="caenid">CAEN ID</label>
                                            <input type="text" class="form-control" id="caenid" name="caenid" placeholder="CAEN ID">
                                        </div>
                                    </div>

                                </div>

                                <button type="submit" class="btn btn-info">Submit <span class="glyphicon glyphicon-search"></span></button>

                            </fieldset>


                        </div>
                    <div class="tab-pane" id="phones">
                        <fieldset>
                            <legend>Phone Numbers</legend>

                            <div class="row">
                                <div class="col-md-3">
                                    <label>Phone Number</label>
                                </div>
                                <div class="col-md-2">
                                    <label>Extension</label>
                                </div>
                                <div class="col-md-2">
                                    <label>Phone Type</label>
                                </div>
                                <div class="col-md-4">
                                    <label>Description</label>
                                </div>
                                <div class="col-md-1">
                                    <label>Restrict?</label>
                                </div>
                            </div>

                            <div class="row">
                                <div class="form-group">
                                    <div class="col-md-1">
                                        <input type="text" class="form-control" id="areacode" name="areacode" placeholder="###" maxlength="3">
                                    </div>
                                    <div class="col-md-1">
                                        <input type="text" class="form-control" id="prefix" name="prefix" placeholder="###" maxlength="3">
                                    </div>
                                    <div class="col-md-1">
                                        <input type="text" class="form-control" id="number" name="number" placeholder="####" maxlength="4">
                                    </div>
                                    <div class="col-md-2">
                                        <input type="text" class="form-control" id="ext" name="ext" placeholder="ext." maxlength="8">
                                    </div>
                                    <div class="col-md-2">
                                        <select class="form-control">
                                        </select>
                                    </div>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control" id="description" name="description">
                                    </div>
                                    <div class="col-md-1">
                                        <label class="checkbox-inline">
                                            <input type="checkbox" id="restrict" value="y">
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <button type="submit" class="btn btn-info">Submit <span class="glyphicon glyphicon-search"></span></button>

                        </fieldset>

                    </form>
                    </div>

                </div>
            </div>
</div>