 <!--<table class="table">
<?php foreach ($person as $p) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($p->FIRSTNAME);?></td>
        <td><?php echo $this->escapeHtml($p->UMID);?></td>
        <td><?php echo $this->escapeHtml($p->UNIQNAME);?></td>
        <td>counter</td>
    </tr>
<?php endforeach; ?>
</table>-->

<div class="col-md-8">
    <div class="well">
        <form role="form">
            <fieldset>
                <legend>Search Results</legend>

            <div class="row">

                <div class="col-md-3">
                    <div class="form-group">
                        <label for="firstname">First Name</label>
                        <input name="firstname" class="form-control" type="text" id="firstname" value="<?php echo $this->escapeHtml($person->FNAME);?>">
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="form-group">
                        <label for="lastname">Last Name</label>
                        <input name="lastname" class="form-control" type="text" id="lastname" value="<?php echo $this->escapeHtml($person->LNAME);?>">
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label for="middlename">Middle Name</label>
                        <input name="middlename" class="form-control" type="text" id="middlename" value="<?php echo $this->escapeHtml($person->MNAME);?>">
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label for="name_suffix">Name Suffix</label>
                        <input name="name_suffix" class="form-control" type="text" id="name_suffix" value="<?php echo $this->escapeHtml($person->NAME_SUFFIX);?>">
                    </div>
                </div>

            </div>

            <div class="row">

                <div class="col-md-3">
                    <div class="form-group">
                        <label for="umid">UM ID</label>
                        <input name="umid" class="form-control" type="text" id="umid" value="<?php echo $this->escapeHtml($person->UMID);?>">
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="form-group">
                        <label for="uniqname">Uniqname</label>
                        <input name="uniqname" class="form-control" type="text" id="uniqname" value="<?php echo $this->escapeHtml($person->UNIQNAME);?>">
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="form-group">
                        <label for="caen_id">Caen ID</label>
                        <input name="caen_id" class="form-control" type="text" id="caen_id" value="<?php echo $this->escapeHtml($person->CAEN_ID);?>">
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="form-group">
                        <label for="nickname">Nickname</label>
                        <input name="nickname" class="form-control" type="text" id="nickname" value="<?php echo $this->escapeHtml($person->NICKNAME);?>">
                    </div>
                </div>

            </div>


            <!-- <div class="one half padded">
                <label for="CARDVERNUM">Card Version Number</label>
                <input readonly id="CARDVERNUM" value="<?php echo $this->escapeHtml($person->CARDVERNUM);?>">
            </div>
            <div class="one half padded">
                <label for="OVERWRITABLE">Overwriteable?</label>
                <input readonly id="OVERWRITABLE" value="<?php echo $this->escapeHtml($person->OVERWRITABLE);?>">
            </div>
            <div class="one half padded">
                <label for="SECURITY_FLAG">Security Flag</label>
                <input readonly id="SECURITY_FLAG" value="<?php echo $this->escapeHtml($person->SECURITY_FLAG);?>">
            </div>
            <div class="one half padded">
                <label for="DATE_CREATED">Date Created</label>
                <input readonly id="DATE_CREATED" value="<?php echo $this->escapeHtml($person->DATE_CREATED);?>">
            </div>
            <div class="one half padded">
                <label for="CREATED_BY">Created By</label>
                <input readonly id="CREATED_BY" value="<?php echo $this->escapeHtml($person->CREATED_BY);?>">
            </div>
            <div class="one half padded">
                <label for="LAST_UPDATE">Last Update</label>
                <input readonly id="LAST_UPDATE" value="<?php echo $this->escapeHtml($person->LAST_UPDATE);?>">
            </div>
            <div class="one half padded">
                <label for="LAST_UPDATED_BY">Last Updated By</label>
                <input readonly id="LAST_UPDATED_BY" value="<?php echo $this->escapeHtml($person->LAST_UPDATED_BY);?>">
            </div> -->

            </fieldset>
        </form>
    </div>
</div>