 <!--<table class="table">
<?php foreach ($person as $p) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($p->FIRSTNAME);?></td>
        <td><?php echo $this->escapeHtml($p->UMID);?></td>
        <td><?php echo $this->escapeHtml($p->UNIQNAME);?></td>
        <td>counter</td>
    </tr>
<?php endforeach; ?>
</table>-->

<div class="row">
    <div class="one third padded">
        <form>
            <fieldset>
                <legend>Search Results</legend>
            <div class="one half padded">
                <label for="firstname">First Name</label>
                <input readonly id="firstname" value="<?php echo $this->escapeHtml($person->FNAME);?>">
            </div>
            <div class="one half padded">
                <label for="lastname">Last Name</label>
                <input readonly id="lastname" value="<?php echo $this->escapeHtml($person->LNAME);?>">
            </div>
            <div class="one half padded">
                <label for="umid">UM ID</label>
                <input readonly id="umid" value="<?php echo $this->escapeHtml($person->UMID);?>">
            </div>
            <div class="one half padded">
                <label for="uniqname">Uniqname</label>
                <input readonly id="uniqname" value="<?php echo $this->escapeHtml($person->UNIQNAME);?>">
            </div>
            <div class="one half padded">
                <label for="CAEN_ID">Caen ID</label>
                <input readonly id="CAEN_ID" value="<?php echo $this->escapeHtml($person->CAEN_ID);?>">
            </div>
            <div class="one half padded">
                <label for="MNAME">Middle Name</label>
                <input readonly id="MNAME" value="<?php echo $this->escapeHtml($person->MNAME);?>">
            </div>
            <div class="one half padded">
                <label for="CARDVERNUM">Card Version Number</label>
                <input readonly id="CARDVERNUM" value="<?php echo $this->escapeHtml($person->CARDVERNUM);?>">
            </div>
            <div class="one half padded">
                <label for="OVERWRITABLE">Overwriteable?</label>
                <input readonly id="OVERWRITABLE" value="<?php echo $this->escapeHtml($person->OVERWRITABLE);?>">
            </div>
            <div class="one half padded">
                <label for="SECURITY_FLAG">Security Flag</label>
                <input readonly id="SECURITY_FLAG" value="<?php echo $this->escapeHtml($person->SECURITY_FLAG);?>">
            </div>
            <div class="one half padded">
                <label for="DATE_CREATED">Date Created</label>
                <input readonly id="DATE_CREATED" value="<?php echo $this->escapeHtml($person->DATE_CREATED);?>">
            </div>
            <div class="one half padded">
                <label for="CREATED_BY">Created By</label>
                <input readonly id="CREATED_BY" value="<?php echo $this->escapeHtml($person->CREATED_BY);?>">
            </div>
            <div class="one half padded">
                <label for="LAST_UPDATE">Last Update</label>
                <input readonly id="LAST_UPDATE" value="<?php echo $this->escapeHtml($person->LAST_UPDATE);?>">
            </div>
            <div class="one half padded">
                <label for="LAST_UPDATED_BY">Last Updated By</label>
                <input readonly id="LAST_UPDATED_BY" value="<?php echo $this->escapeHtml($person->LAST_UPDATED_BY);?>">
            </div>
            <div class="one half padded">
                <label for="NAME_SUFFIX">Name Suffix</label>
                <input readonly id="NAME_SUFFIX" value="<?php echo $this->escapeHtml($person->NAME_SUFFIX);?>">
            </div>
            <div class="one half padded">
                <label for="NICKNAME">Nickname</label>
                <input readonly id="NICKNAME" value="<?php echo $this->escapeHtml($person->NICKNAME);?>">
            </div>

        </fieldset>
        </form>
    </div>
</div>